// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDxCQTh7vIL7nukVRgCD5NqQL9Oc_oqQ',
    appId: '1:282036476767:web:2aa09cee30b8f61b9a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    authDomain: 'adast-425404.firebaseapp.com',
    storageBucket: 'adast-425404.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmbcfy-m0zedpbfYH2Do-Di-Nx8xl84JM',
    appId: '1:282036476767:android:6111fbdc8c7dc3e49a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    storageBucket: 'adast-425404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIepHwXbL-BAgC3789GrvF77Ig61-pT_k',
    appId: '1:282036476767:ios:4335f19f66020c979a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    storageBucket: 'adast-425404.appspot.com',
    androidClientId: '282036476767-3on9ml5cqbf5et8jvf2292u8ovt2mk8k.apps.googleusercontent.com',
    iosClientId: '282036476767-f8eoq206011qhu54i9pvcal9jbou2tff.apps.googleusercontent.com',
    iosBundleId: 'com.example.adast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIepHwXbL-BAgC3789GrvF77Ig61-pT_k',
    appId: '1:282036476767:ios:4335f19f66020c979a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    storageBucket: 'adast-425404.appspot.com',
    androidClientId: '282036476767-3on9ml5cqbf5et8jvf2292u8ovt2mk8k.apps.googleusercontent.com',
    iosClientId: '282036476767-f8eoq206011qhu54i9pvcal9jbou2tff.apps.googleusercontent.com',
    iosBundleId: 'com.example.adast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNDxCQTh7vIL7nukVRgCD5NqQL9Oc_oqQ',
    appId: '1:282036476767:web:4d5e73910c419fce9a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    authDomain: 'adast-425404.firebaseapp.com',
    storageBucket: 'adast-425404.appspot.com',
  );

}