// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDxCQTh7vIL7nukVRgCD5NqQL9Oc_oqQ',
    appId: '1:282036476767:web:6032c2a187e1917f9a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    authDomain: 'adast-425404.firebaseapp.com',
    storageBucket: 'adast-425404.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmbcfy-m0zedpbfYH2Do-Di-Nx8xl84JM',
    appId: '1:282036476767:android:6111fbdc8c7dc3e49a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    storageBucket: 'adast-425404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxkBWUp2YRqyXDUYRV5OXDKkJJTyLfrk',
    appId: '1:888534327765:ios:beb1dc3bad9dea74e01d5c',
    messagingSenderId: '888534327765',
    projectId: 'adast-53666',
    storageBucket: 'adast-53666.appspot.com',
    iosBundleId: 'com.example.adast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHxkBWUp2YRqyXDUYRV5OXDKkJJTyLfrk',
    appId: '1:888534327765:ios:beb1dc3bad9dea74e01d5c',
    messagingSenderId: '888534327765',
    projectId: 'adast-53666',
    storageBucket: 'adast-53666.appspot.com',
    iosBundleId: 'com.example.adast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNDxCQTh7vIL7nukVRgCD5NqQL9Oc_oqQ',
    appId: '1:282036476767:web:7a597150791db39e9a34ea',
    messagingSenderId: '282036476767',
    projectId: 'adast-425404',
    authDomain: 'adast-425404.firebaseapp.com',
    storageBucket: 'adast-425404.appspot.com',
  );

}